# Generated by Django 4.0.5 on 2022-08-07 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('choose', models.CharField(choices=[('ar', 'Статья'), ('ne', 'Новости')], max_length=2)),
                ('title', models.CharField(max_length=60)),
                ('text', models.TextField()),
                ('rating_post', models.IntegerField(default=0)),
                ('liked_by', models.ManyToManyField(related_name='liked_posts', to=settings.AUTH_USER_MODEL)),
                ('post_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsApps.author')),
                ('post_category', models.ManyToManyField(to='NewsApps.category')),
            ],
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsApps.category')),
                ('post_rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsApps.post')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_comment', models.TextField()),
                ('comment_date', models.DateTimeField(null=True)),
                ('rating_comment', models.IntegerField(default=0)),
                ('comment_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsApps.post')),
                ('comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
